# Change these first
owner: kominfo-denpasar # Your GitHub organization or username, where this repository lives
repo: status-website # The name of this repository

sites:
  - name: SIMAKDIHATI
    url: https://simpeg.denpasarkota.go.id
  - name: DIVOS
    url: https://divos.denpasarkota.go.id
  - name: SPBE
    url: https://spbe.denpasarkota.go.id
  - name: TemanRita
    url: https://temanrita.denpasarkota.go.id

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-website
  logoUrl: https://raw.githubusercontent.com/kominfo-denpasar/maintenance-page/main/logo.png
  name: Status Website
  introTitle: "**Status Layanan & API Lingkungan Pemerintah Kota Denpasar**"
  introMessage: Tool monitoring untuk mengecek status website, layanan & API, powered entirely by GitHub & Upptime.. [**Web Portal Pemerintah Kota Denpasar**](https://denpasarkota.go.id). [**Web Status v2**](https://status.dpskota.my.id/status/layanan)
  navbar:
    - title: Beranda
      href: /status-website
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
